resources:
- deployment.yaml
- service.yaml
- ingress.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: /
  newName: /
  newTag: 442c162e44aebf9f073834b560b18c02beae0771
- name: 533267391963.dkr.ecr.us-east-1.amazonaws.com/app
  newName: 533267391963.dkr.ecr.us-east-1.amazonaws.com/app
  newTag: latest
