resources:
- deployment.yaml
- service.yaml
- ingress.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 471112967827.dkr.ecr.us-east-1.amazonaws.com/app
  newName: 471112967827.dkr.ecr.us-east-1.amazonaws.com/app
  newTag: latest
