resources:
- deployment.yaml
- service.yaml
- ingress.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: /
  newName: /
  newTag: 88f11cb323c2b0d32bea63a09642faebc007ea21
- name: 211125439598.dkr.ecr.us-east-1.amazonaws.com/app
  newName: 211125439598.dkr.ecr.us-east-1.amazonaws.com/app
  newTag: latest
