resources:
- deployment.yaml
- service.yaml
- ingress.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: /
  newName: /
  newTag: c02351d9fbf70bde9383ab6696d00a2ad5fbf10b
- name: 767398127572.dkr.ecr.us-east-1.amazonaws.com/app
  newName: 767398127572.dkr.ecr.us-east-1.amazonaws.com/app
  newTag: latest
