applications:
  enabled: true
  items:
    guestbook:
      name: guestbook
      namespace: argocd
      project: default
      source:
        repoURL: "https://github.com/argoproj/argocd-example-apps"
        targetRevision: HEAD
        path: guestbook
      destination:
        server: "https://kubernetes.default.svc"
        namespace: guestbook
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - "CreateNamespace=true"
