name: Destroy 
on:
  workflow_dispatch:   # run manually from GitHub Actions UI
    inputs:
      environment:
        description: "Environment to destroy (e.g., dev, prod)"
        required: true
        default: dev

jobs:
  destroy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write   # for OIDC auth to AWS
      contents: read

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup OpenTofu
        uses: opentofu/setup-opentofu@v1
        with:
          tofu_version: 1.10.0

      - name: Configure AWS creds
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/GitHubActionsTofuRole
          aws-region: us-east-1

      - name: Init
        run: tofu init -input=false

      - name: Destroy
        run: |
          tofu destroy -auto-approve \
            -var-file=${{ github.event.inputs.environment }}.tfvars
